# Identity Infra pipeline
# https://aka.ms/yaml

trigger:
  - none
  
variables:
    azureServiceConnection: 'ServiceConnection-ELZ'
    location: 'westus2'
    locationShort: 'wus2'
    templateFile: 'hub/identity/identity-main.bicep'
    parametersFile: 'hub/identity/identity-main.bicepparam'
    subscriptionId: '5a718e73-cce6-49e2-af77-023ea133c332'
    
    # action: 'what-if'
    action: 'create'     
  
pool:
    # vmImage: ubuntu-latest
    vmImage: 'windows-latest'
  
stages:
  - stage: 'MDP'
    displayName: 'Deploy Identity'
    jobs:
    - deployment: 'Deploy_Identity'
      environment: 'Identity'
      timeoutInMinutes: '360'
      strategy:
       runOnce:
          deploy:
             steps:
              - checkout: self
  # Bicep deployment tasks            
              - task: AzureCLI@2
                displayName: "Deploy Identity Resources"
                inputs:
                  azureSubscription: $(azureServiceConnection)
                  scriptType: bash
                  scriptLocation: inlineScript
                  inlineScript: |
                    pwd
                    az account set --subscription $(subscriptionId)
                    az deployment sub $(action) --location $(location) --template-file $(templateFile) --parameters $(parametersFile)
                    
  